env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0 # "off"или 0- отключить правило
  import/extensions: 
  - error # "error" или 2 - включить правило как ошибку
  - ignorePackages # правило требует использования расширений для всех операторов импорта, кроме импорта пакетов.
  - js: always # всегда будет принудительно использоваться расширение .js
  no-underscore-dangle: ["error", {"allow": ["__filename","__dirname"]} # правила для свисающих подчеркиваний, (2 = error)
  ]

